# Generated by Django 5.0.3 on 2024-04-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=10)),
                ('dob', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('country', models.CharField(blank=True, default='', max_length=15)),
                ('postal_code', models.CharField(blank=True, default='', max_length=15)),
                ('password', models.CharField(blank=True, default='', max_length=15)),
                ('status', models.CharField(blank=True, default='', max_length=15)),
                ('confirm_password', models.CharField(blank=True, default='', max_length=15)),
                ('actionBtn', models.CharField(blank=True, default='', max_length=15)),
                ('card_number', models.CharField(blank=True, default='', max_length=30)),
                ('pin_number', models.CharField(blank=True, default='', max_length=4)),
                ('security_code', models.CharField(blank=True, default='', max_length=3)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number_and_name', models.CharField(blank=True, default='', max_length=150)),
                ('transType', models.CharField(blank=True, default='', max_length=15)),
                ('amount', models.CharField(blank=True, default='', max_length=15)),
                ('balance_after', models.CharField(blank=True, default='', max_length=15)),
                ('balance_before', models.CharField(blank=True, default='', max_length=15)),
                ('summary', models.CharField(blank=True, default='', max_length=250)),
                ('date', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
